{
  "openapi": "3.0.0",
  "info": {
    "title": "API Gerenciador de Contatos",
    "description": "Tem como objetivo o cadastro de contatos",
    "contact": {
      "email": "l.alves85@live.com"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost/3000/",
      "description": "API de testes"
    }
  ],
  "paths": {
    "/client": {
      "post": {
        "summary": "Cadastro de Cliente",
        "description": "Essa rota será responsável por cadastrar um novo Cliente",
        "tags": ["Client"],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Client"
              },
              "examples": {
                "cliente": {
                  "value": {
                    "name": "Exemplo de Nome do Cliente",
                    "email": "exemplo@mail.com",
                    "phone": "0000000000",
                    "password": "1234"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Requisição Inválida"
          },
          "409": {
            "description": "Cliente já existe"
          },
          "201": {
            "description": "Criado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Client"
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Listar Clientes",
        "description": "Essa rota será responsável por listar todos os Clientes",
        "tags": ["Client"],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Client"
                }
              }
            }
          }
        }
      }
    },
    "/client/{id}": {
      "patch": {
        "summary": "Alterar dados do Cliente",
        "description": "Essa rota será responsável por alterar os dados de um Cliente",
        "tags": ["Client"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Cliente pelo ID",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Client"
              },
              "examples": {
                "cliente": {
                  "value": {
                    "name": "Novo Exemplo de Nome do Cliente",
                    "email": "novoeexemplo@mail.com",
                    "phone": "333333333",
                    "password": "1234"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "invalid token"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Client"
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Deletar Cliente",
        "description": "Essa rota será responsável por remover um Cliente",
        "tags": ["Client"],
        "responses": {
          "401": {
            "description": "invalid token"
          },
          "204": {
            "description": "No Content"
          }
        }
      }
    },
    "/contact": {
      "post": {
        "summary": "Cadastro de Contatos",
        "description": "Essa rota será responsável por cadastrar um novo Contato",
        "tags": ["Contato"],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Contato"
              },
              "examples": {
                "contato": {
                  "value": {
                    "name": "Nome do Contato",
                    "email": "exemplocontato@mail.com",
                    "phone": "0000000000"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "Requisição Inválida"
          },
          "409": {
            "description": "Contato já existe"
          },
          "201": {
            "description": "Criado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Contato"
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Listar Contatos",
        "description": "Essa rota será responsável por listar todos os Contatos do Cliente",
        "tags": ["Contact"],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Contact"
                }
              }
            }
          }
        }
      }
    },
    "/contact/{id}": {
      "patch": {
        "summary": "Alterar dados do Contato",
        "description": "Essa rota será responsável por alterar os dados de um Contato",
        "tags": ["Contact"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Contado pelo ID",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Contact"
              },
              "examples": {
                "cliente": {
                  "value": {
                    "name": "Novo Exemplo de Nome do Contato",
                    "email": "novoeexemplocontato@mail.com",
                    "phone": "333333333",
                    "password": "1234"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "401": {
            "description": "invalid token"
          },
          "404": {
            "description": "Contact not found"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Contact"
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Deletar Contato",
        "description": "Essa rota será responsável por remover um Contato",
        "tags": ["Contact"],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "401": {
            "description": "invalid token"
          },
          "204": {
            "description": "No Content"
          }
        }
      }
    },
    "/forgotpassword": {
      "post": {
        "summary": "Recuperar Senha",
        "description": "Essa rota será responsável por recuperar a senha do cliente",
        "tags": ["Cliente"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string"
                  }
                },
                "required": ["email"]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Cliente não encontrado"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Client": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "phone": {
            "type": "string"
          }
        }
      },
      "Contact": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "phone": {
            "type": "string"
          },
          "secondEmail": {
            "type": "string"
          },
          "secondPhone": {
            "type": "string"
          },
          "githubUser": {
            "type": "string"
          },
          "linkedinUser": {
            "type": "string"
          },
          "portfolioUrl": {
            "type": "string"
          }
        }
      }
    }
  },
  "securitySchemes": {
    "bearerAuth": {
      "type": "http",
      "scheme": "bearer",
      "bearerFormat": "JWT"
    }
  }
}
